name: LÖVE GameHub Android CI

on:
  push:
    branches: [ "main", "capy/*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: "-Dorg.gradle.jvmargs='-Xmx4G'"

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Prepare submodules
      run: |
        git submodule update --recursive
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install ninja-build cmake

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleNormalRecordDebug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: LOVE-GameHub-Debug
        path: ./app/build/outputs/apk/normalRecord/debug/app-normal-record-debug.apk
